---
title: "HR Transactions: Sick Calendars"
date: "Data as of `r fs::file_info(here::here('../pr-data-pins/data-raw/emptrans/api_year-merged/emp-trans_2023.CSV'))$birth_time |> strftime(format = '%Y-%m-%d')`"
params:
  branch: 1
output:
  html_document:
    self_contained: true
    fig_width: 12
    fig_height: 8
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, out.width='3000px')
#| label: libraries
#| output: false
library(conflicted)
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
library(here)
library(employer)
library(tidyverse)
library(glue)
library(targets)
```

```{r}
#| label: filter-employee_get-years
store <- here::here("_targets")
tar_load(calendars, store = store, branches = params$branch)
df <- calendars
tar_load(data_employee, store = store)

employee_no <- unique(df$employee_no)

employee <- data_employee |> 
  filter(employee_no == !!employee_no) |> 
  pull(employee)

```

## Employee: `r employee` {.tabset .tabset-pills}

::: {.panel-tabset .column-screen-inset}
```{r}
#| label: knit-child-years
#| results: asis
options(knitr.duplicate.label = "allow")

year_reports <- lapply(
  df$year |> unique(),
  function(y) {
    knitr::knit_child(
      here("Rmd" ,"calendar_child.Rmd"),
      envir = environment(),
      quiet = TRUE
      )
    }
  )

cat(unlist(year_reports), sep = '\n')
```
:::
